[Pins]
DHT11_PIN = "D4"
SOIL_MOISTURE_ADC_CHANNEL = "P0"
RELAY_PIN_PUMP = "D17"
LED_PIN_RED = "D27"
LED_PIN_YELLOW = "D22"
LED_PIN_GREEN = "D5"

[voltage_soil_moisture]
SOIL_MOISTURE_VOLTAGE_DRY = 2.21
SOIL_MOISTURE_VOLTAGE_WET = 0.935

[soil_moisture]
SOIL_MOISTURE_THRESHOLD_LOW = 30.0
SOIL_MOISTURE_THRESHOLD_OK_LOW = 45.0
SOIL_MOISTURE_THRESHOLD_OK_HIGH = 70.0

[timeing_config]
SENSOR_READ_INTERVAL_SECONDS = 10
PUMP_ON_DURATION_SECONDS = 3.0
PUMP_COOLDOWN_SECONDS = 600


