@startchen

entity Device{
ID <<key>>
Name 
Standort
Owner
DevConfig
Pflanzen
}

relationship Zustand {

}

relationship hat_Modell {

}

relationship referenziert{

}

relationship ist_zugewiesen {

}




entity Modell{
ID <<key>> 
Sensoren 
}

entity Pflanze {
PflaConfig
}
entity Messung <<weak>> {
Temp
Bodenfeuchte
Licht
LED_Status
Pumpstatus
}

entity PflanzenTemplate {
Name <<key>> 
Temp
Bodenfeuchte
Licht
}

Device -(1,N)- Zustand
Messung -1- Zustand
Device -(N,1)- hat_Modell 
hat_Modell -(1,N)- Modell 
referenziert -(1,1)- PflanzenTemplate
referenziert -(1,1)- Pflanze
Device -(1,N)- ist_zugewiesen
ist_zugewiesen -1- Pflanze



@endchen
