erDiagram
    Device }o--|| Model: has
    Model ||--o{ ModelDeviceSensor: has
    Model ||--o{ ModelPlantSensor: has
    Model ||--o{ Actuator: has
    ModelDeviceSensor ||--o{ Sensor: has
    ModelPlantSensor ||--o{ Sensor: has
    Plant }o--|| Device: has

    Device {
        int id PK
        string name
        string location
        int model FK
        int[] plants FK
    }

    Model {
        int id PK
        string name
        int slot_count
        int[] device_sensors FK
        int[] plant_sensors FK
        int[] actuators FK
    }

    ModelDeviceSensor {
        int id PK
        int sensorId FK
        string field_name
    }

    ModelPlantSensor {
        int id PK
        int sensorId FK
        int slot_number
    %% Der Name des Felds im JSON
    %% Bsp:
    %% manfred: "30c"
        string field_name
    }

    Sensor {
        int id PK
        string name
        string type
        string unit
        number accuracy
        number min
        number max
    }

    Actuator {
        int id PK
        string name
        string type
    }

    Plant {
        int id PK
        string species
        string type FK
    }

    Plant }o--|| PlantType: is

    PlantType {
        string latName PK
        string species
        int[] plantConfigFields FK
    }

    PlantType }|--|| PlantConfigField: has

    PlantConfigField {
        int id PK
        string field_name
        string unit
        number value
    }

    Measurement {
        int ModelDeviceSensor PK
        int timestamp
        number value
    }
