/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./components/Account.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AuthButton: typeof import('./components/AuthButton.vue')['default']
    DeviceCard: typeof import('./components/cards/DeviceCard.vue')['default']
    DevicePanel: typeof import('./components/panel/DevicePanel.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    LoadAndError: typeof import('./components/LoadAndError.vue')['default']
    PlantCard: typeof import('./components/cards/PlantCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
